---
inputs:
- type: git
  service: ${GIT_REPO}
  branch: ${GIT_BRANCH}
  path: .tekton
- type: git
  service: https://github.com/open-toolchain/tekton-catalog
  branch: master
  path: git
triggers:
- type: git
  name: Git PR Trigger
  service: ${GIT_REPO}
  branch: master
  events: {"push":true,"pull_request":false,"pull_request_closed":false}
  eventListener: listener
- type: manual
  name: Manual Trigger
  eventListener: listener
properties:
- name: GIT_REPO
  value: ${GIT_REPO}
  type: text 
- name: GIT_BRANCH
  value: ${GIT_BRANCH}
  type: text 
- name: API_KEY
  value: ${API_KEY}
  type: SECURE
- name: REGISTRY_REGION_ID
  value: ${REGISTRY_REGION_ID}
  type: text 
- name: REGISTRY_NAMESPACE
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: TARGET_CLUSTER_NAME
  value: ${TARGET_CLUSTER_NAME}
  type: text 
- name: IMAGE_NAME
  value: ${IMAGE_NAME}
  type: text 
- name: TARGET_REGION_ID
  value: ${TARGET_REGION_ID}
  type: text 
- name: TARGET_NAMESPACE
  value: ${TARGET_NAMESPACE}
  type: text 
- name: TARGET_RESOURCE_GROUP
  value: ${TARGET_RESOURCE_GROUP}
  type: text 
- name: COS_PLAN
  value: ${COS_PLAN}
  type: text 
- name: APP_ID_PLAN
  value: ${APP_ID_PLAN}
  type: text 
