apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: 10-build
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: tt10-build
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tt10-build
spec:
  params:
    - name: GIT_REPO
    - name: GIT_BRANCH
    - name: REGISTRY_REGION_ID
    - name: REGISTRY_NAMESPACE
    - name: TARGET_CLUSTER_NAME
    - name: IMAGE_NAME
    - name: TARGET_REGION_ID
    - name: TARGET_NAMESPACE
    - name: TARGET_RESOURCE_GROUP
    - name: COS_PLAN
    - name: APP_ID_PLAN
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-input-parameter-variable
        params:
          - name: task-pvc
            value: pipelinerun-$(uid)-pvc
          - name: GIT_REPO
            value: $(params.GIT_REPO)
          - name: GIT_BRANCH
            value: $(params.GIT_BRANCH)
          - name: REGISTRY_REGION_ID
            value: $(params.REGISTRY_REGION_ID)
          - name: REGISTRY_NAMESPACE
            value: $(params.REGISTRY_NAMESPACE)
          - name: TARGET_CLUSTER_NAME
            value: $(params.TARGET_CLUSTER_NAME)
          - name: IMAGE_NAME
            value: $(params.IMAGE_NAME)
          - name: TARGET_REGION_ID
            value: $(params.TARGET_REGION_ID)
          - name: TARGET_NAMESPACE
            value: $(params.TARGET_NAMESPACE)
          - name: TARGET_RESOURCE_GROUP
            value: $(params.TARGET_RESOURCE_GROUP)
          - name: COS_PLAN
            value: $(params.COS_PLAN)
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  params:
    - name: task-pvc
    - name: GIT_REPO
    - name: GIT_BRANCH
    - name: REGISTRY_REGION_ID
    - name: REGISTRY_NAMESPACE
    - name: TARGET_CLUSTER_NAME
    - name: IMAGE_NAME
    - name: TARGET_REGION_ID
    - name: TARGET_NAMESPACE
    - name: TARGET_RESOURCE_GROUP
    - name: COS_PLAN
    - name: APP_ID_PLAN
  tasks:
    - name: clone
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.task-pvc)
        - name: repository
          value: $(params.GIT_REPO)
        - name: branch
          value: master
    - name: t1
      params:
        - name: task-pvc
          value: $(params.task-pvc)
        - name: GIT_REPO
          value: $(params.GIT_REPO)
        - name: GIT_BRANCH
          value: $(params.GIT_BRANCH)
        - name: REGISTRY_REGION_ID
          value: $(params.REGISTRY_REGION_ID)
        - name: REGISTRY_NAMESPACE
          value: $(params.REGISTRY_NAMESPACE)
        - name: TARGET_CLUSTER_NAME
          value: $(params.TARGET_CLUSTER_NAME)
        - name: IMAGE_NAME
          value: $(params.IMAGE_NAME)
        - name: TARGET_REGION_ID
          value: $(params.TARGET_REGION_ID)
        - name: TARGET_NAMESPACE
          value: $(params.TARGET_NAMESPACE)
        - name: TARGET_RESOURCE_GROUP
          value: $(params.TARGET_RESOURCE_GROUP)
        - name: COS_PLAN
          value: $(params.COS_PLAN)
        - name: APP_ID_PLAN
          value: $(params.APP_ID_PLAN)
        - name: script
          value: ./scripts/pipeline-BUILD.sh
      taskRef:
        name: gasket
      runAfter:
        - clone
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gasket
spec:
  inputs:
    params:
      - name: task-pvc
      - name: GIT_REPO
      - name: GIT_BRANCH
      - name: REGISTRY_REGION_ID
      - name: REGISTRY_NAMESPACE
      - name: TARGET_CLUSTER_NAME
      - name: IMAGE_NAME
      - name: TARGET_REGION_ID
      - name: TARGET_NAMESPACE
      - name: TARGET_RESOURCE_GROUP
      - name: COS_PLAN
      - name: APP_ID_PLAN
      - name: script
  steps:
    - name: echoenvvar
      image: l2fprod/bxshell
      env:
        - name: task_pvc
          value: $(inputs.params.task-pvc)
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: API_KEY
        - name: GIT_REPO
          value: $(inputs.params.GIT_REPO)
        - name: GIT_BRANCH
          value: $(inputs.params.GIT_BRANCH)
        - name: REGISTRY_REGION_ID
          value: $(inputs.params.REGISTRY_REGION_ID)
        - name: REGISTRY_NAMESPACE
          value: $(inputs.params.REGISTRY_NAMESPACE)
        - name: TARGET_CLUSTER_NAME
          value: $(inputs.params.TARGET_CLUSTER_NAME)
        - name: IMAGE_NAME
          value: $(inputs.params.IMAGE_NAME)
        - name: TARGET_REGION_ID
          value: $(inputs.params.TARGET_REGION_ID)
        - name: TARGET_NAMESPACE
          value: $(inputs.params.TARGET_NAMESPACE)
        - name: TARGET_RESOURCE_GROUP
          value: $(inputs.params.TARGET_RESOURCE_GROUP)
        - name: COS_PLAN
          value: $(inputs.params.COS_PLAN)
        - name: APP_ID_PLAN
          value: $(inputs.params.APP_ID_PLAN)
        - name: script
          value: $(inputs.params.script)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 00
          echo env task_pvc: $task_pvc
          echo env API_KEY: $API_KEY
          echo env GIT_REPO: $GIT_REPO
          echo env GIT_BRANCH: $GIT_BRANCH
          echo env REGISTRY_REGION_ID: $REGISTRY_REGION_ID
          echo env REGISTRY_NAMESPACE: $REGISTRY_NAMESPACE
          echo env TARGET_CLUSTER_NAME: $TARGET_CLUSTER_NAME
          echo env IMAGE_NAME: $IMAGE_NAME
          echo env TARGET_REGION_ID: $TARGET_REGION_ID
          echo env TARGET_NAMESPACE: $TARGET_NAMESPACE
          echo env TARGET_RESOURCE_GROUP: $TARGET_RESOURCE_GROUP
          echo env COS_PLAN: $COS_PLAN
          echo env APP_ID_PLAN: $APP_ID_PLAN
          echo env script: $script
          ls /working
          echo hi >> /working/hi
          cat /working/hi
          cd /working
          ls -l $script
          cat $script
          # TODO REGISTRY_URL mus be based on TARGET_REGION_ID
          export REGISTRY_URL=us.icr.io
          # TODO BUILD_NUMBER is not needed
          export BUILD_NUMBER=3
          export ARCHIVE_DIR=.
          # Setting HOME explicitly to have ibmcloud plugins available
          export HOME="/root"
          cat /cd-config/toolchain.json
          TOOLCHAIN_REGION=$(jq -r '.region_id' /cd-config/toolchain.json | awk -F: '{print $3}')
          ibmcloud config --check-version false
          ibmcloud login -r $TOOLCHAIN_REGION --apikey $API_KEY
          bash -x $script
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
        - mountPath: /working
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json
