apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: 10-build
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: tt10-build
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding
---
#apikey
#cluster
#Name
#clusterNamespace
#clusterRegion
#registryNamespace
#registryRegion
#repository
#revision

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tt10-build
spec:
  params:
    - name: registryNamespace
    - name: X
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-input-parameter-variable
        params:
          - name: registryNamespace
            value: $(params.registryNamespace)
          - name: X
            value: $(params.X)
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  params:
    - name: registryNamespace
    - name: X
  tasks:
    - name: pipv
      params:
        - name: registryNamespace
          value: $(params.registryNamespace)
        - name: X
          value: $(params.X)
      taskRef:
        name: the-var-task

---
# shared task
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: the-var-task
spec:
  inputs:
    params:
      - name: registryNamespace
      - name: X
  steps:
    - name: echoenvvar
      image: ubuntu
      env:
        - name: registryNamespace
          value: $(inputs.params.registryNamespace)
        - name: X
          value: $(inputs.params.X)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 00
          echo 01 lab2 env registryNamespace: $registryNamespace
          echo 01 lab2 env X: $X
